name: tap_map
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mapbox_maps_flutter: ^2.6.0
  http: ^1.1.0
  flutter_dotenv: ^5.2.1
  geolocator: ^13.0.2
  dio: ^5.7.0
  get_it: ^8.0.3
  talker: ^4.6.0
  get: ^4.6.6
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.3.5
  bloc: ^9.0.0
  flutter_svg: ^2.0.17
  auto_route: ^9.3.0+1
  latlong2: ^0.9.1
  equatable: ^2.0.7
  video_player: ^2.9.3
  tcard: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/svg/
    - assets/png/
    - assets/png/location.png
    













