name: tap_map
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mapbox_maps_flutter: ^2.7.0
  http: ^1.1.0
  flutter_dotenv: ^5.2.1
  geolocator: ^13.0.2
  dio: ^5.7.0
  get_it: ^8.0.3
  talker: ^4.6.0
  get: ^4.6.6
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.5.2
  bloc: ^9.0.0
  flutter_svg: ^2.0.17
  auto_route: ^9.3.0+1
  latlong2: ^0.9.1
  equatable: ^2.0.7
  video_player: ^2.9.3
  tcard: ^1.3.5
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  path_provider: ^2.1.5
  go_router: ^14.8.1
  image_picker: ^1.1.2
  qr_flutter: ^4.1.0
  share_plus: ^10.1.4
  flutter_timezone: ^4.1.0
  app_links: ^6.4.0
  synchronized: ^3.3.0+3
  firebase_messaging: ^15.2.5
  firebase_core: ^3.13.0
  flutter_local_notifications: ^19.1.0
  flutterfire_cli: ^1.2.0
  url_launcher: ^6.2.4
  device_info_plus: ^9.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/svg/
    - assets/png/
    - assets/jpeg/
    

flutter_native_splash:
  color: "#FFFFFF" 
  image: assets/png/logo_TM.png
  android: true
  ios: true
  fullscreen: true
  android_12:
    color: "#FFFFFF"
    image: assets/png/logo_TM.png