// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf8gDsM8rEAis9ztiooFbf3ftB93mVuLU',
    appId: '1:665756653815:web:43a54890889f4ff689dbf2',
    messagingSenderId: '665756653815',
    projectId: 'tapmap-46ff4',
    authDomain: 'tapmap-46ff4.firebaseapp.com',
    storageBucket: 'tapmap-46ff4.firebasestorage.app',
    measurementId: 'G-0K5XYF1K4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz0lMiZcvSB-HIhDe9baEBdI3IpVnMPak',
    appId: '1:665756653815:android:446b2eb5fb59bde189dbf2',
    messagingSenderId: '665756653815',
    projectId: 'tapmap-46ff4',
    storageBucket: 'tapmap-46ff4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_lFY3kgmksI4JA3VmMuMH44yVgwfbDgg',
    appId: '1:665756653815:ios:c024697f9f32f0fd89dbf2',
    messagingSenderId: '665756653815',
    projectId: 'tapmap-46ff4',
    storageBucket: 'tapmap-46ff4.firebasestorage.app',
    iosBundleId: 'com.tommy.tapmap.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf8gDsM8rEAis9ztiooFbf3ftB93mVuLU',
    appId: '1:665756653815:web:eb3fcbcfd5ccb23589dbf2',
    messagingSenderId: '665756653815',
    projectId: 'tapmap-46ff4',
    authDomain: 'tapmap-46ff4.firebaseapp.com',
    storageBucket: 'tapmap-46ff4.firebasestorage.app',
    measurementId: 'G-MQD1J9Y4WZ',
  );
}